name: nisave
description: "A new Flutter project."
publish_to: 'none' # This line prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.0.12
  http: ^1.2.1
  provider: ^6.0.0
  flutter_secure_storage: ^9.0.0
  modal_progress_hud_nsn: ^0.5.1-nullsafety-1
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  shared_preferences: ^2.0.13
  connectivity_plus: ^6.0.3
  cloud_firestore: ^4.17.3
  intl: ^0.19.0
  flutter_otp_text_field: ^1.1.3+2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Group1.svg
    - assets/images/Illustration.svg
    - assets/images/Illustration2.svg
    - assets/images/Illustration3.svg
    - assets/images/back.svg
    - assets/images/corner.svg
    - assets/images/middle.svg
    - assets/images/flags.svg
    - assets/images/fingerprint.svg
    - assets/images/default_avatar.svg
